apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z2cphf9rj-python
  janus-idp.io/tekton: z2cphf9rj-python
  backstage.io/kubernetes-id: z2cphf9rj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z2cphf9rj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
